---
functional:
  - Пользователь должен авторизоваться на сайте
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность настраивать параметры игры при создании
  - Пользователь должен иметь возможность присоединиться к созданной другим пользователем игре
  - Пользователь должен иметь возможность достигать целей игры
  - Пользователь должен иметь возможность завершить игру по истечению времени или по достижению целей игры
  - Пользователь должен иметь возможность завершить игру без достижения цели игры или истечения времени на игру
  - Пользователь должен видеть код, который пишет оппонент
  - Игра должна считаться завершенной, если оба пользователя покинули игру
  - Сайт должен сохранять историю игр 
non-functional:
  - Дизайн сайта должен быть удобен для использования на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность повторно подключиться к игре при потере соединения до завершения игры
  - Пользователь должен иметь возможность оставить обратную связь об ошибках в задачах
